### ISSUE TITLE
Imperfect gold standard model often fails at the prior distribution stage

### ISSUE THREAD

**Issue by tommorris168** [CRSU-Apps/MetaBayesDTA#14]
This is the case whenever there are fewer than four reference standards. I have fixed the bug offline and will do it formally soon. There are two separate bugs, one when the number of prior distributions is one, two, or three, and an additional bug when it is one. This latter bug also affects the main model.

**Comment by tommorris168** [comment]
@RyanJField Are you happy for this issue to be closed?

**Comment by RyanJField** [comment]
Yes, I will close it now.

**Comment by tommorris168** [comment]
Reopening this because the fix has only been applied when the prior distributions are set on the probability scale, not on the logit scale.

**Comment by tommorris168** [comment]
Both cases now done.
