### ISSUE TITLE
Add ability to specify a seed

### ISSUE THREAD

**Issue by tommorris168** [CRSU-Apps/MetaBayesDTA#2]
Possibly also display the seed used if one isn't specified.

**Comment by RyanJField** [comment]
Hi Tom, the seed can be set for the models in the advanced options, or by default is set to 123.
![Screenshot 2023-08-18 at 08 11 17](https://github.com/CRSU-Apps/MetaBayesDTA/assets/57794045/ca0f312a-934e-4172-8e19-962b9bce459c)

I agree this should be printed somewhere perhaps under model diagnostics or model results.
