### ISSUE TITLE
# in Stan files

### ISSUE THREAD

**Issue by tommorris168** [CRSU-Apps/MetaBayesDTA#6]
The #'s in comments in the Stan files cause errors and need to be removed.

**Comment by tommorris168** [comment]
This is causing me problems now so I'm going to do it at the same time as issue #14.

**Comment by tommorris168** [comment]
I believe this is now fixed.

**Comment by tommorris168** [comment]
@RyanJField Are you happy for this issue to be closed?

**Comment by RyanJField** [comment]
Yes, I'll close it now
